
title: DSA-Questions
description: A Jekyll theme for documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://just-the-docs.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: imkrunalkanojiya/DSA-Questions-using-JavaScript # for github-metadata

permalink: pretty

theme: just-the-docs
